language: python
python:
  - '3.6'

services:
  - docker

before_script: pip install docker-compose

script:
  - docker-compose run app sh -c "python manage.py test && flake8"
# ทุกครั้งที่ push ไป github จะ run scirpt
