version: "3"

# เอาไว้ commande ของ docker ระบุกรณีมีหลายๆ services เช่น django-compose run app sh -c "django-admin.py startproject app ." คือใช้ services app เพื่อสร้าง dev project
services:
  app:
    build:
      context: .
    ports:
      - "8000:8000" # map host กับ server
    volumes:
      - ./app:/app
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
    environment: # map ไปาหา db postgres และอ้างอิงไปถึง settings.py
      - DB_HOST=db
      - DB_NAME=app
      - DB_USER=postgres
      - DB_PASSWORD=1234
    depends_on: #ต้องให้ postgres run ก่อน django app
      - db
  db:
    image: postgres:10-alpine # เอามาจาก docker hub
    environment: # ตั้งค่าให้กับ db เมื่อ postgres start
      - POSTGRE_DB=app
      - POSTGRE_USER=postgres
      - POSTGRE_PASSWORD=1234
